print('Aluno: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nNro Matrícula: XXXXXXXXXXX\n-------------------------------------\nPrograma referente ao exercício 6\n-------------------------------------',)
n1 = int(input('Entre com o 1° número: '))
n2 = int(input('Entre com o 2° número: '))
n3 = int(input('Entre com o 3° número: '))
print('O resultado é:', n1+n2+n3)
print('-------------------------------------')
