print('Aluno: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nNro Matrícula: XXXXXXXXXXX\n-------------------------------------\nPrograma referente ao exercício 10\n-------------------------------------',)
linha1 = ('  ____   _____   __  __    ___    _   ____  ')
linha2 = (' / ___| |  ___| |  \/  |  / _ \  / | | ___| ')
linha3 = ('| |  _  | |_    | |\/| | | | | | | | |___ \ ')
linha4 = ('| |_| | |  _|   | |  | | | |_| | | |  ___) |')
linha5 = (' \____| |_|     |_|  |_|  \___/  |_| |____/')
print(linha1)
print(linha2)
print(linha3)
print(linha4)
print(linha5)
print('-------------------------------------')
