print('Aluno: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nNro Matrícula: XXXXXXXXXXX\n-------------------------------------\nPrograma referente ao exercício 12\n-------------------------------------',)
a = int(input('Insira a altura do triângulo: '))
b = int(input('Insira o lado do triângulo: '))
print('A área é:', (a*b)/2)
print('-------------------------------------')